feat: clarify the original developers
hal-shu-sato/apm-data pull request #36
Opened 2021-11-06 04:42 UTC by mitosagi

## Description

Include the name of the author of the derived package in the xml. This PR is related to https://github.com/hal-shu-sato/apm/issues/174 .

## Related Issue

## How Has This Been Tested?

- The current version of apm is able to read this xml correctly.

## Checklist:

- [x] Updated the modification date in `mod.xml`.

2021-11-06 10:44 UTC, hal-shu-sato requested changes
Thank you for the implementation.
I want to fix the README decorations.

2021-11-06 10:44 UTC, hal-shu-sato commented on README.en.md
> +- /packages/package/originalDeveloper: The name of the developer of the package from which it was derived
```suggestion
- _/packages/package/originalDeveloper_: The name of the developer of the package from which it was derived
```

2021-11-06 10:44 UTC, hal-shu-sato commented on README.md
> +- /packages/package/originalDeveloper: 派生元パッケージの開発者
```suggestion
- _/packages/package/originalDeveloper_: 派生元パッケージの開発者
```

2021-11-07 00:32 UTC, mitosagi commented
Corrected.

2021-11-07 02:53 UTC, hal-shu-sato approved these changes
Thank you for fixing them.

2021-11-07 02:53 UTC, merged